### ISSUE TITLE
Openai error

### ISSUE THREAD

**Issue by Gizdulock** [Gizdulock/Discord-chat-bot-with-openai-support#1]
/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/handleCommand.js:45
      const response = await openai.Completion.create({
                                               ^

TypeError: Cannot read properties of undefined (reading 'create')
    at Object.execute (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/handleCommand.js:45:48)
    at handleCommand (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/handleCommand.js:17:11)
    at Client.<anonymous> (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/bot.js:29:3)
    at Client.emit (node:events:513:28)
    at InteractionCreateAction.handle (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/node_modules/discord.js/src/client/actions/InteractionCreate.js:83:12)
    at module.exports [as INTERACTION_CREATE] (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/node_modules/discord.js/src/client/websocket/WebSocketShard.js:493:22)
    at WebSocketShard.onMessage (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/node_modules/discord.js/src/client/websocket/WebSocketShard.js:327:10)
    at callListener (/home/pogoweb/ChatGPT/discord_chatgpt_test/Discord-chat-bot-with-openai-support/node_modules/ws/lib/event-target.js:290:14)

Node.js v18.16.0

**Comment by Gizdulock** [comment]
> As mentioned in the plan, we need to investigate the OpenAI SDK installation and ensure that the API key is correct. We can see that the API key is being set from the environment variable `OPENAI_API_KEY`. Therefore, we need to make sure that this environment variable is set and contains the correct API key.
> 
> If the environment variable is not set or contains an incorrect API key, we need to update it with the correct API key. If the OpenAI SDK is not installed, we need to install it using `npm install openai`. If the SDK is already installed, we can try reinstalling it using `npm install --force openai`.
> 
> Once we have updated the API key and/or reinstalled the SDK, we can try running the code again and see if the error has been resolved.
> 
> Current plan usage: NaN%
> 
> **Have feedback or need help?** Send me an email to [support@codeautopilot.com](mailto:support@codeautopilot.com) - my name is Fábio [Join us on Discord](https://discord.gg/r72ykfvyx7)
